embeddings: TEI factor to new embedder client pattern
tmc/langchaingo pull request #396
Opened 2023-12-04 21:54 UTC by pattonjp

### PR Checklist

- [ ] Read the [Contributing documentation](https://github.com/tmc/langchaingo/blob/main/CONTRIBUTING.md).
- [ ] Read the [Code of conduct documentation](https://github.com/tmc/langchaingo/blob/main/CODE_OF_CONDUCT.md).
- [ ] Name your Pull Request title clearly, concisely, and prefixed with the name of the primarily affected package you changed according to [Good commit messages](https://go.dev/doc/contribute#commit_messages) (such as `memory: add interfaces for X, Y` or `util: add whizzbang helpers`).
- [ ] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `Fixes #123`).
- [ ] Describes the source of new concepts.
- [ ] References existing implementations as appropriate.
- [ ] Contains test coverage for new functions.
- [ ] Passes all [`golangci-lint`](https://golangci-lint.run/) checks.

2023-12-04 22:10 UTC, pattonjp commented
examples ci build is failing due to new dependency.

2023-12-05 00:37 UTC, eliben reviewed
Thanks!

2023-12-05 00:37 UTC, eliben commented on vectorstores/milvus/milvus.go
> -	initialized      bool
The changes in this file seem unrelated to the main goal of the PR, or am I missing something? It'd be good to keep the PR for a single purpose only

2023-12-05 00:37 UTC, eliben commented on llms/tei/text_embeddings_inference..go
> +package tei
Maybe it's worth adding a comment here explaining this package? Specifically, it's not a usual LangChainGo LLM, but only a shell for invoking an embeddings API.

2023-12-08 14:21 UTC, eliben commented
@pattonjp friendly ping - do you intend to continue with this PR?

2023-12-08 17:37 UTC, pattonjp commented
after the embeddings factor, it appears that the tei embeddings client is no longer needed. i am now able to use openai llm as client to my local tei instance.

2023-12-08 18:29 UTC, eliben requested changes

2023-12-08 18:29 UTC, eliben commented on chroma_vectorstore_example
This binary file was removed recently - seems like some sort of rebase artifact? Can you make sure it's not added back?

2023-12-08 18:29 UTC, eliben commented
> @eliben after the embeddings factor, it appears that the tei embeddings client is no longer needed. i am now able to use openai llm as client to my local tei instance.

That's a great outcome :)

2023-12-09 21:47 UTC, tmc approved these changes
LGTM

2023-12-09 21:48 UTC, merged