feat: add WithKeepSeparator option for RecursiveCharacter
tmc/langchaingo pull request #721
Opened 2024-03-26 10:05 UTC by zhangi

### PR Checklist

- [ ] Read the [Contributing documentation](https://github.com/tmc/langchaingo/blob/main/CONTRIBUTING.md).
- [ ] Read the [Code of conduct documentation](https://github.com/tmc/langchaingo/blob/main/CODE_OF_CONDUCT.md).
- [ ] Name your Pull Request title clearly, concisely, and prefixed with the name of the primarily affected package you changed according to [Good commit messages](https://go.dev/doc/contribute#commit_messages) (such as `memory: add interfaces for X, Y` or `util: add whizzbang helpers`).
- [ ] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `Fixes #123`).
- [ ] Describes the source of new concepts.
- [ ] References existing implementations as appropriate.
- [ ] Contains test coverage for new functions.
- [ ] Passes all [`golangci-lint`](https://golangci-lint.run/) checks.

2024-03-27 01:49 UTC, zhangi commented on textsplitter/options.go
> +// WithKeepSeparator set the keep_separator for a text splitter.
updated comments for WithKeepSeparator option.

2024-03-30 03:46 UTC, devalexandre requested changes
don't need update go.mod

2024-03-30 03:47 UTC, devalexandre commented on textsplitter/options.go
> +// resulting split text. When it is set to False, the separators are not included
add in description the default value

2024-04-01 06:30 UTC, zhangi commented
> don't need update go.mod

can elaborate a bit more on the reason? The go.mod is automatically updated after my running 'go mod tidy'. There seems to be a direct dependency from [here](https://github.com/tmc/langchaingo/blob/main/llms/mistral/mistralmodel.go#L8)

2024-04-01 06:30 UTC, zhangi commented on textsplitter/options.go
> +// resulting split text. When it is set to False, the separators are not included
updated the default value in comments.

2024-05-07 04:45 UTC, tmc approved these changes
LGTM

2024-05-07 04:47 UTC, merged